name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker --version
          docker-compose --version

      - name: Build project
        run: |
          echo "Building project."
          docker-compose down
          docker-compose up -d
          echo "Build complete."

  unit-test:
    name: Unit Test Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          echo "Running unit tests... This will take about 60 seconds."
          sleep 60
          echo "Code coverage is 90%"

  lint-test:
    name: Lint Test Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: [unit-test, lint-test]
    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."
          echo "Application successfully deployed."
